### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by VertofChest** [JordoVR/EasyQuestSwitch#16]
NO tutorials... NO guides... NO user support or dev contact... How am I supposed to use this?

**Comment by JordoVR** [comment]
Sorry for the delay, github notifications have not been working out much for me.
To use, after installing, go to window -> Easy Quest Switch and click the setup button, then add an entry and drag a component into the field, you can then choose options (depending on the component) for Windows vs Android, when you switch the platform it'll automatically apply those changes.
This image is a good visual explainer.
![68747470733a2f2f692e696d6775722e636f6d2f6159766634796c2e706e67](https://github.com/JordoVR/EasyQuestSwitch/assets/9134625/4e2c2370-501e-4229-825d-b0c9132d4f89)
