### ISSUE TITLE
EasyQuestSwitch makes Unity Editor hang

### ISSUE THREAD

**Issue by aljowen** [JordoVR/EasyQuestSwitch#27]
![image](https://github.com/vrchat-community/EasyQuestSwitch/assets/16223353/97347c84-6446-4576-ac70-379ebb61eee4)

Hi,
I used to have issues when using Unity 2019 where my project would hang every 10-15min requiring a Unity restart, I had no idea what was causing the issues. When I updated to Unity 2022.3 that issue went away completely and I was able to be way more productive. But now that I have updated to the most recent version of EasyQuestSwitch the issue has come back again. Unity UI keeps hanging all the time, and when doing bakery renders it gets stuck constantly.

I used to find that opening the Unity Profiler and enabling deep traces and disabling it again every 10 mins or so used to keep the issue at bay. But I could never find the source of the issue beyond Unity UI hanging.

In Unity 2022.3 I now get the above messages when trying to do a bakery render that show what is causing the whole thing to hang and crash.

**Comment by JordoVR** [comment]
This was fixed in the newly released 1.4.0.
https://github.com/vrchat-community/EasyQuestSwitch/releases/tag/v1.4.0
Do note that one of the features of 1.4.0 might cause Bakery to hang while it waits for your input, but you can disable it in the settings.
