### ISSUE TITLE
Not actually switching targets in latest

### ISSUE THREAD

**Issue by bdragon28** [JordoVR/EasyQuestSwitch#28]
I am currently having to manually go to Easy Quest Switch and force apply PC settings / force apply Quest settings on the Settings because the OnSceneOpened() code was commented out and is no longer re-checking the build target when opening scenes.

**Comment by Faxmashine** [comment]
Sorry for the trouble! This feature was removed because of false positives when switching targets. (EQS would ask people to apply settings when it wasn't necessary)

We're thinking of a solution!

**Comment by JordoVR** [comment]
This feature was reintroduced in 1.4.0.
https://github.com/vrchat-community/EasyQuestSwitch/releases/tag/v1.4.0
