### ISSUE TITLE
Needs optimization

### ISSUE THREAD

**Issue by Legoman99573** [JordoVR/EasyQuestSwitch#4]
This is nice, but a problem occurs when editing it in the Easy Quest Switch window as it causes the editor to hang sometimes or slow down when you modify multiple objects added to what you want to modify. Other than that, its a nice resource to use.

**Comment by JordoVR** [comment]
A new upcoming version of EasyQuestSwitch modifies the list display system to be more performant, look out for that.
I'll close this issue when it's released and ping you.

**Comment by JordoVR** [comment]
Solved in the v1.1 release
https://github.com/JordoVR/EasyQuestSwitch/releases/tag/v1.1
